window.FACTLENS_STRINGS = {
  en: {
    simpleView: "Simple view",
    speakClaim: "Speak claim",
    stopListening: "Stop listening",
    listening: "Listening. Speak now.",
    voiceUnsupported: "Voice input is not supported in this browser.",
    voicePermissionDenied: "Microphone access was denied.",
    voiceError: "Voice input stopped. Try again.",
    transcriptAdded: "Speech added to the claim.",
    readAloud: "Read result aloud",
    stopReading: "Stop reading",
    speechUnsupported: "Read-aloud is not supported in this browser.",
    languageCaution: "Signal analysis is optimized for English. Hindi and Telugu text may not receive reliable results.",
    translateBeforeCheck: "The current signal analysis is optimized for English. Translate this claim into English before checking.",
    trafficFake: "High-risk signals found.",
    trafficReview: "Check a reliable source.",
    trafficReal: "Fewer warning signals found.",
    trafficSummary: "Language cues are not proof. Verify the original source.",
  },
  hi: {
    simpleView: "सरल दृश्य",
    speakClaim: "दावा बोलें",
    stopListening: "सुनना बंद करें",
    listening: "सुन रहे हैं। अब बोलें।",
    voiceUnsupported: "इस ब्राउज़र में वॉइस इनपुट उपलब्ध नहीं है।",
    voicePermissionDenied: "माइक्रोफ़ोन की अनुमति नहीं मिली।",
    voiceError: "वॉइस इनपुट रुक गया। फिर कोशिश करें।",
    transcriptAdded: "बोले गए शब्द दावे में जोड़ दिए गए।",
    readAloud: "नतीजा सुनें",
    stopReading: "पढ़ना रोकें",
    speechUnsupported: "इस ब्राउज़र में पढ़कर सुनाने की सुविधा उपलब्ध नहीं है।",
    languageCaution: "संकेत विश्लेषण अभी अंग्रेज़ी के लिए बेहतर है। हिंदी और तेलुगु परिणाम विश्वसनीय नहीं हो सकते।",
    translateBeforeCheck: "अभी संकेत विश्लेषण अंग्रेज़ी के लिए बेहतर है। जांच से पहले दावे का अंग्रेज़ी अनुवाद करें।",
    trafficFake: "जोखिम वाले संकेत मिले।",
    trafficReview: "विश्वसनीय स्रोत से जांचें।",
    trafficReal: "चेतावनी के कम संकेत मिले।",
    trafficSummary: "भाषा के संकेत प्रमाण नहीं हैं। मूल स्रोत की जांच करें।",
  },
  te: {
    simpleView: "సులభ వీక్షణం",
    speakClaim: "వాదనను మాట్లాడండి",
    stopListening: "వినడం ఆపు",
    listening: "వింటున్నాం. ఇప్పుడు మాట్లాడండి.",
    voiceUnsupported: "ఈ బ్రౌజర్లో వాయిస్ ఇన్‌పుట్‌కు మద్దతు లేదు.",
    voicePermissionDenied: "మైక్రోఫోన్ అనుమతి నిరాకరించబడింది.",
    voiceError: "వాయిస్ ఇన్‌పుట్ ఆగింది. మళ్లీ ప్రయత్నించండి.",
    transcriptAdded: "మీ మాటలు వాదనలో జోడించబడ్డాయి.",
    readAloud: "ఫలితాన్ని వినండి",
    stopReading: "చదవడం ఆపు",
    speechUnsupported: "ఈ బ్రౌజర్లో చదివి వినిపించే సదుపాయం లేదు.",
    languageCaution: "సంకేత విశ్లేషణ ప్రస్తుతం ఇంగ్లీష్‌కు అనుకూలంగా ఉంది. హిందీ, తెలుగు ఫలితాలు నమ్మదగినవి కాకపోవచ్చు.",
    translateBeforeCheck: "సంకేత విశ్లేషణ ప్రస్తుతం ఇంగ్లీష్‌కు అనుకూలంగా ఉంది. తనిఖీకి ముందు ఈ వాదనను ఇంగ్లీష్‌లోకి అనువదించండి.",
    trafficFake: "ప్రమాద సూచనలు ఎక్కువగా ఉన్నాయి.",
    trafficReview: "నమ్మదగిన మూలంతో తనిఖీ చేయండి.",
    trafficReal: "హెచ్చరిక సూచనలు తక్కువగా ఉన్నాయి.",
    trafficSummary: "భాషా సంకేతాలు రుజువు కావు. అసలు మూలాన్ని తనిఖీ చేయండి.",
  },
};